# Generated by Django 2.1.5 on 2020-06-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defaillance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(blank=True, choices=[('1', 'Accident imprévisible'), ('2', 'Cause intrinsèque detectable'), ('3', 'Cause intrinsèque non detectable'), ('4', "Défaut d'entretien"), ('5', 'Mauvaise intervention antérieure'), ('6', 'Mauvaise conduite'), ('7', 'Consignes non respectées'), ('8', 'Autres')], max_length=64, null=True)),
                ('origine', models.CharField(blank=True, choices=[('1', 'Origine mécanique'), ('2', 'Origine électrique'), ('3', 'Origine électronique'), ('4', 'Origine hydraulique')], max_length=32, null=True)),
                ('gravite', models.CharField(blank=True, choices=[('1', 'CRITIQUE'), ('2', 'MAJEURE'), ('3', 'MINEURE')], max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoIntervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineDefaillante', models.CharField(max_length=64)),
                ('dateDefaillance', models.DateField()),
                ('dateIntervention', models.DateField()),
                ('durationIntervention', models.FloatField()),
                ('dateServiceOn', models.DateField()),
                ('defaillanceList', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machineBoard.Defaillance')),
            ],
        ),
        migrations.CreateModel(
            name='MaintainerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTeam', models.CharField(max_length=64)),
                ('passwordTeam', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='infointervention',
            name='maintainerTeam',
            field=models.ManyToManyField(related_name='teamwork', to='machineBoard.MaintainerTeam'),
        ),
    ]
