# Generated by Django 2.1.5 on 2020-06-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machineBoard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infointervention',
            name='maintainerTeam',
        ),
        migrations.AddField(
            model_name='infointervention',
            name='maintainerTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machineBoard.MaintainerTeam'),
        ),
    ]
