# Generated by Django 2.1.5 on 2020-06-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineBoard', '0002_auto_20200626_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineName', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='infointervention',
            name='MachineDefaillante',
        ),
        migrations.AddField(
            model_name='machine',
            name='infoInterventionAll',
            field=models.ManyToManyField(related_name='machine', to='machineBoard.InfoIntervention'),
        ),
    ]
